using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using PartnerTechSeries.AI.HOL.FaceAPI;

namespace PartnerTechSeries
{
    public class Facade
    {
        //Paste the 'storetoserver' Function Code here...

        //Paste the 'User_ImageValidation' Function Code here...

        //Paste the 'User_Registration' Function Code here...

        //Paste the 'RandomGestureShow' Function Code here...

        //Paste the 'User_Verification' Function Code here...

        //Paste the 'Admin_ImageShow' Function Code here...

        //Paste the 'Admin_ImageEdit' Function Code here...

        //Paste the 'Admin_ImageUpdate' Function Code here...

        //Paste the 'Admin_GestureShow' Function Code here...

        //Paste the 'Admin_GestureEdit' Function Code here...

        //Paste the 'Admin_GestureUpdate' Function Code here...

        //Paste the 'Admin_GestureAdd' Function Code here...

        //Paste the 'Admin_AuditLogShow' Function Code here...

        //Paste the 'QualityControlChecker' Function Code here...

        //Paste the 'DocumentVerificationHandler' Function Code here...


    }//End of Facade Class

}//End of namespace HeroSolutions